# Generated by Django 2.1.5 on 2024-03-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baskets',
            name='id',
        ),
        migrations.AlterField(
            model_name='baskets',
            name='basketId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
