# Generated by Django 2.1.5 on 2024-03-08 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'product', 'purchase_date')},
        ),
    ]
