# Generated by Django 5.0.1 on 2024-02-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questAI", "0002_alter_userprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="postcode",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
