# Generated by Django 2.1.5 on 2024-03-08 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questAI', '0002_auto_20240308_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='like',
            field=models.BooleanField(default=True, verbose_name='Like/Dislike'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questAI.Products', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='reviewId',
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('username', 'productId')},
        ),
    ]
