# Generated by Django 2.1.5 on 2024-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAI', '0002_auto_20240306_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baskets',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
