# Generated by Django 2.1.5 on 2024-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questAI', '0003_auto_20240308_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='like',
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=7, verbose_name='Like/Dislike'),
        ),
    ]
