# Generated by Django 5.0.1 on 2024-02-28 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questAI", "0003_userprofile_address_userprofile_postcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
    ]
